import { useState, useEffect } from 'react';
import DataTable from '../../components/ui/DataTable';
import StatusBadge from '../../components/ui/StatusBadge';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../contexts/AuthContext';
import './Reports.css';

export default function Reports() {
  const { user, loading } = useAuth();
  const [reports, setReports] = useState([]);
  const [fetching, setFetching] = useState(false);

  useEffect(() => {
    if (!user) return;
    const fetchReports = async () => {
      setFetching(true);
      const { data } = await supabase
        .from('reports')
        .select('*, applications(company_name, recommended_iso), profiles(full_name)')
        .order('created_at', { ascending: false });
      if (data) {
        const flattened = data.map(r => ({
          ...r,
          company_name: r.applications?.company_name || '—',
          recommended_iso: r.applications?.recommended_iso || '—',
          generated_by: r.profiles?.full_name || '—',
        }));
        setReports(flattened);
      }
      setFetching(false);
    };
    fetchReports();
  }, [user]);

  if (!user || loading) return <div className="page-container"><p>Loading reports...</p></div>;

  const columns = [
    { key: 'id', label: 'Report ID', render: (val) => (
      <span style={{ fontFamily: 'monospace', color: 'var(--color-accent)' }}>{String(val).substring(0,8)}</span>
    )},
    { key: 'company_name', label: 'Company' },
    { key: 'recommended_iso', label: 'Standard' },
    { key: 'generated_by', label: 'Generated By' },
    { key: 'status', label: 'Status', render: (val) => <StatusBadge status={val || 'completed'} /> },
    { key: 'created_at', label: 'Date', render: (val) => new Date(val).toLocaleDateString() },
  ];

  return (
    <div className="page-container">
      <div className="page-header">
        <div>
          <h1 className="page-title">Reports</h1>
          <p className="page-subtitle">Platform audit logs and analytical documents</p>
        </div>
      </div>

      {fetching ? (
        <p>Loading reports database...</p>
      ) : (
        <DataTable
          columns={columns}
          data={reports}
          emptyMessage="No reports have been generated yet."
        />
      )}
    </div>
  );
}
