// Full IAF country list (matches the `countries` seed in supabase_accreditation_setup.sql).
// Use this for dropdowns / multi-select UIs where a round-trip to Supabase is unnecessary.
// The DB table remains the source of truth for saved relationships (cb_countries.country_id).

export const IAF_COUNTRIES = [
  'United States','Canada','Australia','France','Germany','Iceland','Ireland','Italy',
  'Spain','Sweden','Austria','Belgium','Finland','Czech Republic','Denmark','Norway',
  'United Kingdom','Switzerland','New Zealand','Russian Federation','Portugal',
  'Netherlands','Isle of Man','Afghanistan','Aland Islands','Albania','Algeria',
  'American Samoa','Andorra','Angola','Anguilla','Antarctica','Antigua and Barbuda',
  'Argentina','Armenia','Aruba','Azerbaijan','Bahamas','Bahrain','Bangladesh',
  'Barbados','Belarus','Belize','Benin','Bermuda','Bhutan',
  'Bolivia, Plurinational State of','Bosnia and Herzegovina','Botswana','Bouvet Island',
  'Brazil','British Indian Ocean Territory','Brunei Darussalam','Bulgaria',
  'Burkina Faso','Burundi','Cambodia','Cameroon','Cape Verde','Cayman Islands',
  'Central African Republic','Chad','Chile','China','Christmas Island',
  'Cocos (Keeling) Islands','Colombia','Comoros','Congo',
  'Congo, the Democratic Republic of the','Cook Islands','Costa Rica',"Cote d'Ivoire",
  'Croatia','Cuba','Cyprus','Djibouti','Dominica','Dominican Republic','Ecuador',
  'Egypt','El Salvador','Equatorial Guinea','Eritrea','Estonia','Ethiopia',
  'Falkland Islands (Malvinas)','Faroe Islands','Fiji','French Guiana',
  'French Polynesia','French Southern Territories','Gabon','Gambia','Georgia','Ghana',
  'Gibraltar','Greece','Greenland','Grenada','Guadeloupe','Guam','Guatemala',
  'Guernsey','Guinea','Guinea-Bissau','Guyana','Haiti',
  'Heard Island and McDonald Islands','Holy See (Vatican City State)','Honduras',
  'Hong Kong','Hungary','India','Indonesia','Iran, Islamic Republic of','Iraq',
  'Israel','Jamaica','Japan','Jersey','Jordan','Kazakhstan','Kenya','Kiribati',
  "Korea, Democratic People's Republic of",'Korea, Republic of','Kuwait','Kyrgyzstan',
  "Lao People's Democratic Republic",'Latvia','Lebanon','Lesotho','Liberia',
  'Libyan Arab Jamahiriya','Liechtenstein','Lithuania','Luxembourg','Macau',
  'North Macedonia','Madagascar','Malawi','Malaysia','Maldives','Mali','Malta',
  'Marshall Islands','Martinique','Mauritania','Mauritius','Mayotte','Mexico',
  'Micronesia, Federated States of','Moldova, Republic of','Monaco','Mongolia',
  'Montenegro','Montserrat','Morocco','Mozambique','Myanmar','Namibia','Nauru',
  'Nepal','Netherlands Antilles','New Caledonia','Nicaragua','Niger','Nigeria','Niue',
  'Norfolk Island','Northern Mariana Islands','Oman','Pakistan','Palau',
  'Palestinian Territory, Occupied','Panama','Papua New Guinea','Paraguay','Peru',
  'Philippines','Pitcairn','Poland','Puerto Rico','Qatar','Reunion','Romania','Rwanda',
  'Saint Barthelemy','Saint Helena','Saint Kitts and Nevis','Saint Lucia',
  'Saint Martin (French part)','Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines','Samoa','San Marino','Sao Tome and Principe',
  'Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone','Singapore','Slovakia',
  'Slovenia','Solomon Islands','Somalia','South Africa',
  'South Georgia and the South Sandwich Islands','Sri Lanka','Sudan','Suriname',
  'Svalbard and Jan Mayen','Swaziland','Syrian Arab Republic','Chinese Taipei',
  'Tajikistan','Tanzania, United Republic of','Thailand','Timor-Leste','Togo',
  'Tokelau','Tonga','Trinidad and Tobago','Tunisia','Turkey','Turkmenistan',
  'Turks and Caicos Islands','Tuvalu','Uganda','Ukraine','United Arab Emirates',
  'United States Minor Outlying Islands','Uruguay','Uzbekistan','Vanuatu',
  'Venezuela, Bolivarian Republic of','Vietnam','Virgin Islands, British',
  'Virgin Islands, U.S','Wallis and Futuna','Western Sahara','Yemen','Zambia',
  'Zimbabwe','Kosovo',
];
